export const ROUTER_NAVIGATE = 'ROUTER_NAVIGATE'

export const MESSAGE_SET = 'MESSAGE_SET'
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR'

export const PLAYLISTS_LOAD_REQUEST = 'PLAYLISTS_LOAD_REQUEST'
export const PLAYLISTS_LOAD_SUCCESS = 'PLAYLISTS_LOAD_SUCCESS'
export const PLAYLISTS_SEARCH_SET = 'PLAYLISTS_SEARCH_SET'

export const SESSION_BOOTSTRAP_COMPLETE = 'SESSION_BOOTSTRAP_COMPLETE'

export const TRACKS_LOAD_REQUEST = 'TRACKS_LOAD_REQUEST'
export const TRACKS_LOAD_SUCCESS = 'TRACKS_LOAD_SUCCESS'

export const TRACKFEATURES_LOAD_REQUEST = 'TRACKFEATURES_LOAD_REQUEST'
export const TRACKFEATURES_LOAD_SUCCESS = 'TRACKFEATURES_LOAD_SUCCESS'